FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Expose the Streamlit port
EXPOSE 8501

# Command to run the frontend (0.0.0.0 is required for Docker routing)
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]